<?php

return [
    // Lead time (hours) before a task's due date at which a `task_due`
    // reminder is generated by the `notifications:send-due` command.
    'lead_hours' => (int) env('REMINDER_LEAD_HOURS', 24),
];
