<?php

return [
    // Lead time (hours) before a task's due date at which a `task_due`
    // reminder is generated by the `notifications:send-due` command.
    'lead_hours' => (int) env('REMINDER_LEAD_HOURS', 24),

    // How long a read notification stays around before the daily
    // `notifications:prune` command deletes it. Unread notifications are
    // never pruned.
    'retention_days' => (int) env('NOTIFICATIONS_RETENTION_DAYS', 30),
];
