name: taskflow
services:
  backend:
    build:
      args:
        UID: ${USER_UID:-1000}
        GID: ${USER_GID:-33}
      context: ..
      dockerfile: docker/image-backend/Dockerfile
    container_name: taskflow-backend
    working_dir: /var/www/html
    user: "${USER_UID:-1000}:${USER_GID:-33}"
    volumes:
      - ../backend:/var/www/html
    env_file:
      - ../.env

  frontend:
    build:
      context: ..
      dockerfile: docker/image-frontend/Dockerfile
    container_name: taskflow-frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules


  nginx:
    image: nginx:alpine
    container_name: taskflow-nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ../backend:/var/www/html:ro
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  frontend_node_modules:
